# TS1
CUDA_VISIBLE_DEVICES=1 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 1 -p /project_data/ramanan/achakrav/4D-PLS/results/predictions/Kitti360/TS1_updated_vocab -o ../results/metrics/Kitti360_refresh_20cm/TS1_updated_vocab &
CUDA_VISIBLE_DEVICES=1 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 1 -p /project_data/ramanan/achakrav/4D-PLS/results/predictions/Kitti360/TS1_updated_vocab_dagger -o ../results/metrics/Kitti360_refresh_20cm/TS1_updated_vocab_dagger &
CUDA_VISIBLE_DEVICES=1 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 1 -p /project_data/ramanan/mganesin/Panoptic-PolarNet/out/Kitti360/TS1 -o ../results/metrics/Kitti360_refresh_20cm/PolarSeg_TS1 &
CUDA_VISIBLE_DEVICES=1 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 1 -p /project_data/ramanan/achakrav/4D-PLS/results/predictions/Kitti360/hlps_agnostic_regressor_TS1_updated_vocab -o ../results/metrics/Kitti360_refresh_20cm/hlps_agnostic_regressor_TS1 &
CUDA_VISIBLE_DEVICES=1 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 1 -p /project_data/ramanan/achakrav/4D-PLS/results/predictions/Kitti360/hlps_unk_regressor_TS1_updated_vocab -o ../results/metrics/Kitti360_refresh_20cm/hlps_unk_regressor_TS1 &
# TS2
CUDA_VISIBLE_DEVICES=6 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 2 -p /project_data/ramanan/achakrav/4D-PLS/results/predictions/Kitti360/TS2_updated_vocab -o ../results/metrics/Kitti360_refresh_20cm/TS2_updated_vocab &
CUDA_VISIBLE_DEVICES=6 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 2 -p /project_data/ramanan/achakrav/4D-PLS/results/predictions/Kitti360/TS2_updated_vocab_dagger -o ../results/metrics/Kitti360_refresh_20cm/TS2_updated_vocab_dagger &
CUDA_VISIBLE_DEVICES=6 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 2 -p /project_data/ramanan/mganesin/Panoptic-PolarNet/out/Kitti360/TS2 -o ../results/metrics/Kitti360_refresh_20cm/PolarSeg_TS2 &
CUDA_VISIBLE_DEVICES=6 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 2 -p /project_data/ramanan/mganesin/4D-PLS/results/predictions/Kitti360/hlps_agnostic_regressor_TS2_updated_building -o ../results/metrics/Kitti360_refresh_20cm/hlps_agnostic_regressor_TS2 &
CUDA_VISIBLE_DEVICES=6 python evaluate_panoptic_kitti360.py -d ../data/Kitti360 -dc ../data/Kitti360/kitti-360.yaml -t 2 -p /project_data/ramanan/achakrav/4D-PLS/results/predictions/Kitti360/hlps_unk_regressor_TS2_updated_vocab -o ../results/metrics/Kitti360_refresh_20cm/hlps_unk_regressor_TS2 &